### ISSUE TITLE
[rollup example] can not import .ts file

### ISSUE THREAD

**Issue by lili21** [microsoft/TypeScript-Babel-Starter#29]
Think about file directory like this,
```
- src
  - index.ts
  - module-a.ts
```

and the source code

```ts
// index.ts

import a from './module-a'
```

this will break rollup .

**Comment by a-tarasyuk** [comment]
@lili21 Thanks. You can check the updated version [here](https://github.com/a-tarasyuk/rollup-typescript-babel). README will be updated after merge PR #30

**Comment by lili21** [comment]
`external` option should be specified I guess. Cause `rollup-plugin-node-resolve` will bundle third party modules.

**Comment by a-tarasyuk** [comment]
@lili21 Actually, this example does not have any external modules. It is the good starting point to see how to use Babel and TypeScript with Rollup., You can extend Rollup config based on your requirements, add `external`, `globals` options or any other Rollup plugins. Anyway, I added these options and links to Rollup docs, in order to avoid confusion. Thanks.
